// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package helloworld

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsHelloWorldErrorReasonGreeterUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == HelloWorldErrorReason_HELLO_WORLD_ERROR_REASON_GREETER_UNSPECIFIED.String() && e.Code == 500
}

func ErrorHelloWorldErrorReasonGreeterUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, HelloWorldErrorReason_HELLO_WORLD_ERROR_REASON_GREETER_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsHelloWorldErrorReasonUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == HelloWorldErrorReason_HELLO_WORLD_ERROR_REASON_USER_NOT_FOUND.String() && e.Code == 500
}

func ErrorHelloWorldErrorReasonUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, HelloWorldErrorReason_HELLO_WORLD_ERROR_REASON_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
