// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.0
// - protoc             v5.27.2
// source: v1/protos/helloworld/greeter.proto

package helloworld

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	gins "github.com/origadmin/toolkits/runtime/kratos/transport/gins"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = new(gin.H)
var _ = gins.NewContext
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const GreeterService_CreateGreeter_OperationName = "/api.v1.services.helloworld.GreeterService/CreateGreeter"
const GreeterService_DeleteGreeter_OperationName = "/api.v1.services.helloworld.GreeterService/DeleteGreeter"
const GreeterService_GetGreeter_OperationName = "/api.v1.services.helloworld.GreeterService/GetGreeter"
const GreeterService_ListGreeter_OperationName = "/api.v1.services.helloworld.GreeterService/ListGreeter"
const GreeterService_PostHello_OperationName = "/api.v1.services.helloworld.GreeterService/PostHello"
const GreeterService_SayHello_OperationName = "/api.v1.services.helloworld.GreeterService/SayHello"
const GreeterService_UpdateGreeter_OperationName = "/api.v1.services.helloworld.GreeterService/UpdateGreeter"

type GreeterServiceGINServer interface {
	CreateGreeter(context.Context, *CreateGreeterRequest) (*CreateGreeterReply, error)
	DeleteGreeter(context.Context, *DeleteGreeterRequest) (*DeleteGreeterReply, error)
	GetGreeter(context.Context, *GetGreeterRequest) (*GetGreeterReply, error)
	ListGreeter(context.Context, *ListGreeterRequest) (*ListGreeterReply, error)
	// PostHello Sends a greeting
	PostHello(context.Context, *GreeterRequest) (*GreeterReply, error)
	// SayHello Sends a greeting
	SayHello(context.Context, *GreeterRequest) (*GreeterReply, error)
	UpdateGreeter(context.Context, *UpdateGreeterRequest) (*UpdateGreeterReply, error)
}

func RegisterGreeterServiceGINServer(router gin.IRouter, srv GreeterServiceGINServer) {
	router.GET("/greeter/:id/hello", _GreeterService_SayHello0_GIN_Handler(srv))
	router.POST("/greeter/:id/hello", _GreeterService_PostHello0_GIN_Handler(srv))
	router.POST("/greeter", _GreeterService_CreateGreeter0_GIN_Handler(srv))
	router.PUT("/greeter/:id", _GreeterService_UpdateGreeter0_GIN_Handler(srv))
	router.DELETE("/greeter/:id", _GreeterService_DeleteGreeter0_GIN_Handler(srv))
	router.GET("/greeter/:id", _GreeterService_GetGreeter0_GIN_Handler(srv))
	router.GET("/greeter", _GreeterService_ListGreeter0_GIN_Handler(srv))
}

func _GreeterService_SayHello0_GIN_Handler(srv GreeterServiceGINServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in GreeterRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		http.SetOperation(ctx, GreeterService_SayHello_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.SayHello(newCtx, &in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
		return
	}
}

func _GreeterService_PostHello0_GIN_Handler(srv GreeterServiceGINServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in GreeterRequest
		if err := gins.BindBody(ctx, &in.Data); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindQuery(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		http.SetOperation(ctx, GreeterService_PostHello_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.PostHello(newCtx, &in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply.Data)
		return
	}
}

func _GreeterService_CreateGreeter0_GIN_Handler(srv GreeterServiceGINServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in CreateGreeterRequest
		if err := gins.BindBody(ctx, &in.Data); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindQuery(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		http.SetOperation(ctx, GreeterService_CreateGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.CreateGreeter(newCtx, &in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
		return
	}
}

func _GreeterService_UpdateGreeter0_GIN_Handler(srv GreeterServiceGINServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in UpdateGreeterRequest
		if err := gins.BindBody(ctx, &in.Data); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindQuery(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		http.SetOperation(ctx, GreeterService_UpdateGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.UpdateGreeter(newCtx, &in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
		return
	}
}

func _GreeterService_DeleteGreeter0_GIN_Handler(srv GreeterServiceGINServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in DeleteGreeterRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		http.SetOperation(ctx, GreeterService_DeleteGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.DeleteGreeter(newCtx, &in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
		return
	}
}

func _GreeterService_GetGreeter0_GIN_Handler(srv GreeterServiceGINServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in GetGreeterRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		http.SetOperation(ctx, GreeterService_GetGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.GetGreeter(newCtx, &in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
		return
	}
}

func _GreeterService_ListGreeter0_GIN_Handler(srv GreeterServiceGINServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in ListGreeterRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			ctx.Error(err)
			return
		}
		http.SetOperation(ctx, GreeterService_ListGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.ListGreeter(newCtx, &in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
		return
	}
}

type GreeterServiceGINClient interface {
	CreateGreeter(ctx context.Context, req *CreateGreeterRequest, opts ...http.CallOption) (rsp *CreateGreeterReply, err error)
	DeleteGreeter(ctx context.Context, req *DeleteGreeterRequest, opts ...http.CallOption) (rsp *DeleteGreeterReply, err error)
	GetGreeter(ctx context.Context, req *GetGreeterRequest, opts ...http.CallOption) (rsp *GetGreeterReply, err error)
	ListGreeter(ctx context.Context, req *ListGreeterRequest, opts ...http.CallOption) (rsp *ListGreeterReply, err error)
	PostHello(ctx context.Context, req *GreeterRequest, opts ...http.CallOption) (rsp *GreeterReply, err error)
	SayHello(ctx context.Context, req *GreeterRequest, opts ...http.CallOption) (rsp *GreeterReply, err error)
	UpdateGreeter(ctx context.Context, req *UpdateGreeterRequest, opts ...http.CallOption) (rsp *UpdateGreeterReply, err error)
}

type GreeterServiceGINClientImpl struct {
	cc *http.Client
}

func NewGreeterServiceGINClient(client *http.Client) GreeterServiceGINClient {
	return &GreeterServiceGINClientImpl{client}
}

func (c *GreeterServiceGINClientImpl) CreateGreeter(ctx context.Context, in *CreateGreeterRequest, opts ...http.CallOption) (*CreateGreeterReply, error) {
	var out CreateGreeterReply
	pattern := "/greeter"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(GreeterService_CreateGreeter_OperationName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Data, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterServiceGINClientImpl) DeleteGreeter(ctx context.Context, in *DeleteGreeterRequest, opts ...http.CallOption) (*DeleteGreeterReply, error) {
	var out DeleteGreeterReply
	pattern := "/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(GreeterService_DeleteGreeter_OperationName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterServiceGINClientImpl) GetGreeter(ctx context.Context, in *GetGreeterRequest, opts ...http.CallOption) (*GetGreeterReply, error) {
	var out GetGreeterReply
	pattern := "/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(GreeterService_GetGreeter_OperationName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterServiceGINClientImpl) ListGreeter(ctx context.Context, in *ListGreeterRequest, opts ...http.CallOption) (*ListGreeterReply, error) {
	var out ListGreeterReply
	pattern := "/greeter"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(GreeterService_ListGreeter_OperationName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterServiceGINClientImpl) PostHello(ctx context.Context, in *GreeterRequest, opts ...http.CallOption) (*GreeterReply, error) {
	var out GreeterReply
	pattern := "/greeter/{id}/hello"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(GreeterService_PostHello_OperationName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Data, &out.Data, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterServiceGINClientImpl) SayHello(ctx context.Context, in *GreeterRequest, opts ...http.CallOption) (*GreeterReply, error) {
	var out GreeterReply
	pattern := "/greeter/{id}/hello"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(GreeterService_SayHello_OperationName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterServiceGINClientImpl) UpdateGreeter(ctx context.Context, in *UpdateGreeterRequest, opts ...http.CallOption) (*UpdateGreeterReply, error) {
	var out UpdateGreeterReply
	pattern := "/greeter/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(GreeterService_UpdateGreeter_OperationName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Data, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
