// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: internal/configs/bootstrap.proto

package configs

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/discovery/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the main configuration structure for an application.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service configuration, including servers, clients, and middlewares.
	Server *ServiceConfig `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Discovery configuration for service registration and discovery.
	Discovery     *v1.Discovery `protobuf:"bytes,2,opt,name=discovery,proto3" json:"discovery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_configs_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_configs_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_configs_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *ServiceConfig {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetDiscovery() *v1.Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

var File_internal_configs_bootstrap_proto protoreflect.FileDescriptor

const file_internal_configs_bootstrap_proto_rawDesc = "" +
	"\n" +
	" internal/configs/bootstrap.proto\x12\aconfigs\x1a\x1einternal/configs/service.proto\x1a$runtime/discovery/v1/discovery.proto\"z\n" +
	"\tBootstrap\x12.\n" +
	"\x06server\x18\x01 \x01(\v2\x16.configs.ServiceConfigR\x06server\x12=\n" +
	"\tdiscovery\x18\x02 \x01(\v2\x1f.runtime.discovery.v1.DiscoveryR\tdiscoveryB<Z:github.com/origadmin/basic-layout/internal/configs;configsb\x06proto3"

var (
	file_internal_configs_bootstrap_proto_rawDescOnce sync.Once
	file_internal_configs_bootstrap_proto_rawDescData []byte
)

func file_internal_configs_bootstrap_proto_rawDescGZIP() []byte {
	file_internal_configs_bootstrap_proto_rawDescOnce.Do(func() {
		file_internal_configs_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_configs_bootstrap_proto_rawDesc), len(file_internal_configs_bootstrap_proto_rawDesc)))
	})
	return file_internal_configs_bootstrap_proto_rawDescData
}

var file_internal_configs_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_configs_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),     // 0: configs.Bootstrap
	(*ServiceConfig)(nil), // 1: configs.ServiceConfig
	(*v1.Discovery)(nil),  // 2: runtime.discovery.v1.Discovery
}
var file_internal_configs_bootstrap_proto_depIdxs = []int32{
	1, // 0: configs.Bootstrap.server:type_name -> configs.ServiceConfig
	2, // 1: configs.Bootstrap.discovery:type_name -> runtime.discovery.v1.Discovery
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_configs_bootstrap_proto_init() }
func file_internal_configs_bootstrap_proto_init() {
	if File_internal_configs_bootstrap_proto != nil {
		return
	}
	file_internal_configs_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_configs_bootstrap_proto_rawDesc), len(file_internal_configs_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_configs_bootstrap_proto_goTypes,
		DependencyIndexes: file_internal_configs_bootstrap_proto_depIdxs,
		MessageInfos:      file_internal_configs_bootstrap_proto_msgTypes,
	}.Build()
	File_internal_configs_bootstrap_proto = out.File
	file_internal_configs_bootstrap_proto_goTypes = nil
	file_internal_configs_bootstrap_proto_depIdxs = nil
}
