// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: configs/bootstrap.proto

package configs

import (
	v11 "github.com/origadmin/runtime/api/gen/go/discovery/v1"
	v1 "github.com/origadmin/runtime/api/gen/go/service/v1"
	v12 "github.com/origadmin/runtime/api/gen/go/source/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the main configuration structure for an application.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service configuration, including servers, clients, and middlewares.
	Service *v1.Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Discovery configuration for service registration and discovery.
	Discovery *v11.Discovery `protobuf:"bytes,2,opt,name=discovery,proto3" json:"discovery,omitempty"`
	// Source configuration for loading external config files.
	Source *v12.Sources `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Generic application settings.
	Setting       *Setting `protobuf:"bytes,4,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_configs_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_configs_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_configs_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetService() *v1.Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Bootstrap) GetDiscovery() *v11.Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *Bootstrap) GetSource() *v12.Sources {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Bootstrap) GetSetting() *Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

var File_configs_bootstrap_proto protoreflect.FileDescriptor

const file_configs_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x17configs/bootstrap.proto\x12\x11origadmin.configs\x1a\x18service/v1/service.proto\x1a\x1cdiscovery/v1/discovery.proto\x1a\x16source/v1/source.proto\x1a\x15configs/setting.proto\"\xd3\x01\n" +
	"\tBootstrap\x12-\n" +
	"\aservice\x18\x01 \x01(\v2\x13.service.v1.ServiceR\aservice\x125\n" +
	"\tdiscovery\x18\x02 \x01(\v2\x17.discovery.v1.DiscoveryR\tdiscovery\x12*\n" +
	"\x06source\x18\x03 \x01(\v2\x12.source.v1.SourcesR\x06source\x124\n" +
	"\asetting\x18\x04 \x01(\v2\x1a.origadmin.configs.SettingR\asettingB\x1aZ\x18internal/configs;configsb\x06proto3"

var (
	file_configs_bootstrap_proto_rawDescOnce sync.Once
	file_configs_bootstrap_proto_rawDescData []byte
)

func file_configs_bootstrap_proto_rawDescGZIP() []byte {
	file_configs_bootstrap_proto_rawDescOnce.Do(func() {
		file_configs_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configs_bootstrap_proto_rawDesc), len(file_configs_bootstrap_proto_rawDesc)))
	})
	return file_configs_bootstrap_proto_rawDescData
}

var file_configs_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_configs_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),     // 0: origadmin.configs.Bootstrap
	(*v1.Service)(nil),    // 1: service.v1.Service
	(*v11.Discovery)(nil), // 2: discovery.v1.Discovery
	(*v12.Sources)(nil),   // 3: source.v1.Sources
	(*Setting)(nil),       // 4: origadmin.configs.Setting
}
var file_configs_bootstrap_proto_depIdxs = []int32{
	1, // 0: origadmin.configs.Bootstrap.service:type_name -> service.v1.Service
	2, // 1: origadmin.configs.Bootstrap.discovery:type_name -> discovery.v1.Discovery
	3, // 2: origadmin.configs.Bootstrap.source:type_name -> source.v1.Sources
	4, // 3: origadmin.configs.Bootstrap.setting:type_name -> origadmin.configs.Setting
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_configs_bootstrap_proto_init() }
func file_configs_bootstrap_proto_init() {
	if File_configs_bootstrap_proto != nil {
		return
	}
	file_configs_setting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configs_bootstrap_proto_rawDesc), len(file_configs_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configs_bootstrap_proto_goTypes,
		DependencyIndexes: file_configs_bootstrap_proto_depIdxs,
		MessageInfos:      file_configs_bootstrap_proto_msgTypes,
	}.Build()
	File_configs_bootstrap_proto = out.File
	file_configs_bootstrap_proto_goTypes = nil
	file_configs_bootstrap_proto_depIdxs = nil
}
