// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: configs/registry.proto

package configs

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/discovery/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registries    []*v1.Discovery        `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_configs_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_configs_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_configs_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Registry) GetRegistries() []*v1.Discovery {
	if x != nil {
		return x.Registries
	}
	return nil
}

var File_configs_registry_proto protoreflect.FileDescriptor

const file_configs_registry_proto_rawDesc = "" +
	"\n" +
	"\x16configs/registry.proto\x12\x11origadmin.configs\x1a$runtime/discovery/v1/discovery.proto\"K\n" +
	"\bRegistry\x12?\n" +
	"\n" +
	"registries\x18\x01 \x03(\v2\x1f.runtime.discovery.v1.DiscoveryR\n" +
	"registriesBb\n" +
	")com.github.origadmin.basic-layout.configsB\fConfigsProtoP\x01Z\x18internal/configs;configs\xf8\x01\x01\xa2\x02\aConfigsb\x06proto3"

var (
	file_configs_registry_proto_rawDescOnce sync.Once
	file_configs_registry_proto_rawDescData []byte
)

func file_configs_registry_proto_rawDescGZIP() []byte {
	file_configs_registry_proto_rawDescOnce.Do(func() {
		file_configs_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configs_registry_proto_rawDesc), len(file_configs_registry_proto_rawDesc)))
	})
	return file_configs_registry_proto_rawDescData
}

var file_configs_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_configs_registry_proto_goTypes = []any{
	(*Registry)(nil),     // 0: origadmin.configs.Registry
	(*v1.Discovery)(nil), // 1: runtime.discovery.v1.Discovery
}
var file_configs_registry_proto_depIdxs = []int32{
	1, // 0: origadmin.configs.Registry.registries:type_name -> runtime.discovery.v1.Discovery
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_configs_registry_proto_init() }
func file_configs_registry_proto_init() {
	if File_configs_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configs_registry_proto_rawDesc), len(file_configs_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configs_registry_proto_goTypes,
		DependencyIndexes: file_configs_registry_proto_depIdxs,
		MessageInfos:      file_configs_registry_proto_msgTypes,
	}.Build()
	File_configs_registry_proto = out.File
	file_configs_registry_proto_goTypes = nil
	file_configs_registry_proto_depIdxs = nil
}
