// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: configs/service.proto

package configs

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/discovery/v1"
	cors "github.com/origadmin/runtime/api/gen/go/runtime/middleware/v1/cors"
	v12 "github.com/origadmin/runtime/api/gen/go/runtime/service/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/storage/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This message is a legacy configuration structure and should be considered for deprecation.
// The definitions within `service.v1.Service`, `discovery.v1.Discovery`, etc., are now the primary source of truth.
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Gins  *ServiceConfig_GINS    `protobuf:"bytes,2,opt,name=gins,proto3" json:"gins,omitempty"`
	Http  *ServiceConfig_HTTP    `protobuf:"bytes,3,opt,name=http,proto3" json:"http,omitempty"`
	Grpc  *ServiceConfig_GRPC    `protobuf:"bytes,4,opt,name=grpc,proto3" json:"grpc,omitempty"`
	// Replaced by middleware.v1.cors.Cors
	Cors *cors.Cors `protobuf:"bytes,100,opt,name=cors,proto3" json:"cors,omitempty"`
	// Replaced by discovery.v1.Discovery
	Registry *v1.Discovery `protobuf:"bytes,200,opt,name=registry,proto3" json:"registry,omitempty"`
	// Replaced by storage.v1.Storage
	Data *v11.Storage `protobuf:"bytes,300,opt,name=data,proto3" json:"data,omitempty"`
	// Replaced by service.v1.Service
	Service       *v12.Service `protobuf:"bytes,500,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_configs_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configs_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_configs_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfig) GetGins() *ServiceConfig_GINS {
	if x != nil {
		return x.Gins
	}
	return nil
}

func (x *ServiceConfig) GetHttp() *ServiceConfig_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *ServiceConfig) GetGrpc() *ServiceConfig_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *ServiceConfig) GetCors() *cors.Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *ServiceConfig) GetRegistry() *v1.Discovery {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *ServiceConfig) GetData() *v11.Storage {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServiceConfig) GetService() *v12.Service {
	if x != nil {
		return x.Service
	}
	return nil
}

// GINS, HTTP, GRPC, and Websocket messages are kept for backward compatibility.
// New projects should define servers directly within the `service.v1.Service` message.
type ServiceConfig_GINS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	UseTls        bool                   `protobuf:"varint,3,opt,name=use_tls,json=useTls,proto3" json:"use_tls,omitempty"`
	CertFile      string                 `protobuf:"bytes,4,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,5,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig_GINS) Reset() {
	*x = ServiceConfig_GINS{}
	mi := &file_configs_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig_GINS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig_GINS) ProtoMessage() {}

func (x *ServiceConfig_GINS) ProtoReflect() protoreflect.Message {
	mi := &file_configs_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig_GINS.ProtoReflect.Descriptor instead.
func (*ServiceConfig_GINS) Descriptor() ([]byte, []int) {
	return file_configs_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceConfig_GINS) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServiceConfig_GINS) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServiceConfig_GINS) GetUseTls() bool {
	if x != nil {
		return x.UseTls
	}
	return false
}

func (x *ServiceConfig_GINS) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ServiceConfig_GINS) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ServiceConfig_GINS) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ServiceConfig_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	UseTls        bool                   `protobuf:"varint,3,opt,name=use_tls,json=useTls,proto3" json:"use_tls,omitempty"`
	CertFile      string                 `protobuf:"bytes,4,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,5,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig_HTTP) Reset() {
	*x = ServiceConfig_HTTP{}
	mi := &file_configs_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig_HTTP) ProtoMessage() {}

func (x *ServiceConfig_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_configs_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig_HTTP.ProtoReflect.Descriptor instead.
func (*ServiceConfig_HTTP) Descriptor() ([]byte, []int) {
	return file_configs_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServiceConfig_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServiceConfig_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServiceConfig_HTTP) GetUseTls() bool {
	if x != nil {
		return x.UseTls
	}
	return false
}

func (x *ServiceConfig_HTTP) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ServiceConfig_HTTP) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ServiceConfig_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ServiceConfig_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	UseTls        bool                   `protobuf:"varint,3,opt,name=use_tls,json=useTls,proto3" json:"use_tls,omitempty"`
	CertFile      string                 `protobuf:"bytes,4,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,5,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig_GRPC) Reset() {
	*x = ServiceConfig_GRPC{}
	mi := &file_configs_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig_GRPC) ProtoMessage() {}

func (x *ServiceConfig_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_configs_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig_GRPC.ProtoReflect.Descriptor instead.
func (*ServiceConfig_GRPC) Descriptor() ([]byte, []int) {
	return file_configs_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ServiceConfig_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServiceConfig_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServiceConfig_GRPC) GetUseTls() bool {
	if x != nil {
		return x.UseTls
	}
	return false
}

func (x *ServiceConfig_GRPC) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ServiceConfig_GRPC) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ServiceConfig_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ServiceConfig_Websocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig_Websocket) Reset() {
	*x = ServiceConfig_Websocket{}
	mi := &file_configs_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig_Websocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig_Websocket) ProtoMessage() {}

func (x *ServiceConfig_Websocket) ProtoReflect() protoreflect.Message {
	mi := &file_configs_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig_Websocket.ProtoReflect.Descriptor instead.
func (*ServiceConfig_Websocket) Descriptor() ([]byte, []int) {
	return file_configs_service_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ServiceConfig_Websocket) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServiceConfig_Websocket) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServiceConfig_Websocket) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServiceConfig_Websocket) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *ServiceConfig_Websocket) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_configs_service_proto protoreflect.FileDescriptor

const file_configs_service_proto_rawDesc = "" +
	"\n" +
	"\x15configs/service.proto\x12\x11origadmin.configs\x1a\x1egoogle/protobuf/duration.proto\x1a$runtime/discovery/v1/discovery.proto\x1a%runtime/middleware/v1/cors/cors.proto\x1a runtime/service/v1/service.proto\x1a runtime/storage/v1/storage.proto\"\xb4\t\n" +
	"\rServiceConfig\x129\n" +
	"\x04gins\x18\x02 \x01(\v2%.origadmin.configs.ServiceConfig.GINSR\x04gins\x129\n" +
	"\x04http\x18\x03 \x01(\v2%.origadmin.configs.ServiceConfig.HTTPR\x04http\x129\n" +
	"\x04grpc\x18\x04 \x01(\v2%.origadmin.configs.ServiceConfig.GRPCR\x04grpc\x124\n" +
	"\x04cors\x18d \x01(\v2 .runtime.middleware.v1.cors.CorsR\x04cors\x12<\n" +
	"\bregistry\x18\xc8\x01 \x01(\v2\x1f.runtime.discovery.v1.DiscoveryR\bregistry\x120\n" +
	"\x04data\x18\xac\x02 \x01(\v2\x1b.runtime.storage.v1.StorageR\x04data\x126\n" +
	"\aservice\x18\xf4\x03 \x01(\v2\x1b.runtime.service.v1.ServiceR\aservice\x1a\xcb\x01\n" +
	"\x04GINS\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x17\n" +
	"\ause_tls\x18\x03 \x01(\bR\x06useTls\x12\x1b\n" +
	"\tcert_file\x18\x04 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x05 \x01(\tR\akeyFile\x128\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\x1a\xcb\x01\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x17\n" +
	"\ause_tls\x18\x03 \x01(\bR\x06useTls\x12\x1b\n" +
	"\tcert_file\x18\x04 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x05 \x01(\tR\akeyFile\x128\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\x1a\xcb\x01\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x17\n" +
	"\ause_tls\x18\x03 \x01(\bR\x06useTls\x12\x1b\n" +
	"\tcert_file\x18\x04 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x05 \x01(\tR\akeyFile\x128\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\x1a\xa9\x01\n" +
	"\tWebsocket\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x128\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeoutB\x1aZ\x18internal/configs;configsb\x06proto3"

var (
	file_configs_service_proto_rawDescOnce sync.Once
	file_configs_service_proto_rawDescData []byte
)

func file_configs_service_proto_rawDescGZIP() []byte {
	file_configs_service_proto_rawDescOnce.Do(func() {
		file_configs_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configs_service_proto_rawDesc), len(file_configs_service_proto_rawDesc)))
	})
	return file_configs_service_proto_rawDescData
}

var file_configs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_configs_service_proto_goTypes = []any{
	(*ServiceConfig)(nil),           // 0: origadmin.configs.ServiceConfig
	(*ServiceConfig_GINS)(nil),      // 1: origadmin.configs.ServiceConfig.GINS
	(*ServiceConfig_HTTP)(nil),      // 2: origadmin.configs.ServiceConfig.HTTP
	(*ServiceConfig_GRPC)(nil),      // 3: origadmin.configs.ServiceConfig.GRPC
	(*ServiceConfig_Websocket)(nil), // 4: origadmin.configs.ServiceConfig.Websocket
	(*cors.Cors)(nil),               // 5: runtime.middleware.v1.cors.Cors
	(*v1.Discovery)(nil),            // 6: runtime.discovery.v1.Discovery
	(*v11.Storage)(nil),             // 7: runtime.storage.v1.Storage
	(*v12.Service)(nil),             // 8: runtime.service.v1.Service
	(*durationpb.Duration)(nil),     // 9: google.protobuf.Duration
}
var file_configs_service_proto_depIdxs = []int32{
	1,  // 0: origadmin.configs.ServiceConfig.gins:type_name -> origadmin.configs.ServiceConfig.GINS
	2,  // 1: origadmin.configs.ServiceConfig.http:type_name -> origadmin.configs.ServiceConfig.HTTP
	3,  // 2: origadmin.configs.ServiceConfig.grpc:type_name -> origadmin.configs.ServiceConfig.GRPC
	5,  // 3: origadmin.configs.ServiceConfig.cors:type_name -> runtime.middleware.v1.cors.Cors
	6,  // 4: origadmin.configs.ServiceConfig.registry:type_name -> runtime.discovery.v1.Discovery
	7,  // 5: origadmin.configs.ServiceConfig.data:type_name -> runtime.storage.v1.Storage
	8,  // 6: origadmin.configs.ServiceConfig.service:type_name -> runtime.service.v1.Service
	9,  // 7: origadmin.configs.ServiceConfig.GINS.timeout:type_name -> google.protobuf.Duration
	9,  // 8: origadmin.configs.ServiceConfig.HTTP.timeout:type_name -> google.protobuf.Duration
	9,  // 9: origadmin.configs.ServiceConfig.GRPC.timeout:type_name -> google.protobuf.Duration
	9,  // 10: origadmin.configs.ServiceConfig.Websocket.timeout:type_name -> google.protobuf.Duration
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_configs_service_proto_init() }
func file_configs_service_proto_init() {
	if File_configs_service_proto != nil {
		return
	}
	file_configs_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_configs_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_configs_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_configs_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configs_service_proto_rawDesc), len(file_configs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configs_service_proto_goTypes,
		DependencyIndexes: file_configs_service_proto_depIdxs,
		MessageInfos:      file_configs_service_proto_msgTypes,
	}.Build()
	File_configs_service_proto = out.File
	file_configs_service_proto_goTypes = nil
	file_configs_service_proto_depIdxs = nil
}
