// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/google/wire"
	"github.com/origadmin/runtime"
	"origadmin/basic-layout/internal/configs"
	"origadmin/basic-layout/internal/mods/secondworld/biz"
	"origadmin/basic-layout/internal/mods/secondworld/dal"
	"origadmin/basic-layout/internal/mods/secondworld/server"
	"origadmin/basic-layout/internal/mods/secondworld/service"
)

// Injectors from wire.go:

// wireApp initializes the application using wire.
func wireApp(rt *runtime.Runtime) (*kratos.App, func(), error) {
	bootstrap, err := provideConfig(rt)
	if err != nil {
		return nil, nil, err
	}
	logger := provideLogger(rt)
	database, cleanup, err := dal.NewDB(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := dal.NewGreeterDal(database, logger)
	secondGreeterAPIClient := biz.NewGreeterClient(greeterRepo, logger)
	greeterService := service.NewGreeterService(secondGreeterAPIClient)
	httpServer, err := server.NewHTTPServer(bootstrap, greeterService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer, err := server.NewGRPCServer(bootstrap, greeterService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := NewKratosApp(rt, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// providerSet for components provided by the runtime.
var runtimeProviderSet = wire.NewSet(
	provideLogger,
	provideConfig,
)

// provideLogger extracts the logger from the runtime instance.
func provideLogger(rt *runtime.Runtime) log.Logger {
	return rt.Logger()
}

// provideConfig extracts and decodes the bootstrap config from the runtime instance.
func provideConfig(rt *runtime.Runtime) (*configs.Bootstrap, error) {
	var bc configs.Bootstrap
	if err := rt.Config().Decode("", &bc); err != nil {
		return nil, err
	}
	return &bc, nil
}

// NewKratosApp creates the final kratos.App from the runtime and transport servers.
func NewKratosApp(rt *runtime.Runtime, hs *http.Server, gs *grpc.Server) *kratos.App {
	servers := []transport.Server{hs, gs}
	return rt.NewApp(servers)
}
