// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	_ "go.uber.org/automaxprocs"

	"origadmin/basic-layout/internal/bootloader"
	"origadmin/basic-layout/internal/configs"
	"origadmin/basic-layout/internal/mods/helloworld/biz"
	"origadmin/basic-layout/internal/mods/helloworld/dal"
	"origadmin/basic-layout/internal/mods/helloworld/server"
	"origadmin/basic-layout/internal/mods/helloworld/service"
)

// Injectors from wire.go:

// buildInjectors init kratos application.
func buildInjectors(contextContext context.Context, bootstrap *configs.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	registrar := bootloader.NewRegistrar(bootstrap, logger)
	database, cleanup, err := dal.NewDB(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterDao := dal.NewGreeterDal(database, logger)
	greeterClient := biz.NewGreeterClient(greeterDao, logger)
	greeterServer := service.NewGreeterServer(greeterClient)
	grpcServer := server.NewGRPCServer(bootstrap, greeterServer, logger)
	httpServer := server.NewHTTPServer(bootstrap, greeterServer, logger)
	injectorServer := &bootloader.InjectorServer{
		Logger:     logger,
		Registrar:  registrar,
		Bootstrap:  bootstrap,
		ServerGRPC: grpcServer,
		ServerHTTP: httpServer,
	}
	app := NewApp(contextContext, injectorServer)
	return app, func() {
		cleanup()
	}, nil
}
