// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"origadmin/basic-layout/internal/bootstrap"
	"origadmin/basic-layout/internal/configs"
	"origadmin/basic-layout/internal/mods/helloworld/biz"
	"origadmin/basic-layout/internal/mods/helloworld/dal"
	"origadmin/basic-layout/internal/mods/helloworld/server"
	"origadmin/basic-layout/internal/mods/helloworld/service"
)

import (
	_ "github.com/origadmin/toolkits/contrib/consul/config"
	_ "github.com/origadmin/toolkits/contrib/consul/registry"
)

// Injectors from wire.go:

// buildInjectors init kratos application.
func buildInjectors(contextContext context.Context, configsBootstrap *configs.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	registrar := bootstrap.NewRegistrar(configsBootstrap)
	database, cleanup, err := dal.NewDB(configsBootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := dal.NewGreeterDal(database, logger)
	helloGreeterAPIClient := biz.NewGreeterClient(greeterRepo, logger)
	helloGreeterAPIServer := service.NewGreeterServer(helloGreeterAPIClient)
	grpcServer := server.NewGRPCServer(configsBootstrap, helloGreeterAPIServer, logger)
	httpServer := server.NewHTTPServer(configsBootstrap, helloGreeterAPIServer, logger)
	injectorServer := &bootstrap.InjectorServer{
		Bootstrap:  configsBootstrap,
		Logger:     logger,
		Registrar:  registrar,
		ServerGRPC: grpcServer,
		ServerHTTP: httpServer,
	}
	app := NewApp(contextContext, injectorServer)
	return app, func() {
		cleanup()
	}, nil
}
