// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-layout/multiple/multiple_sample/internal/conf/pb"
	"basic-layout/multiple/multiple_sample/internal/features/user/biz"
	"basic-layout/multiple/multiple_sample/internal/features/user/data"
	"basic-layout/multiple/multiple_sample/internal/features/user/server"
	"basic-layout/multiple/multiple_sample/internal/features/user/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport"
	"github.com/google/wire"
	"github.com/origadmin/runtime"
	"github.com/origadmin/runtime/api/gen/go/config/data/v1"
	"github.com/origadmin/runtime/api/gen/go/config/transport/v1"
)

import (
	_ "basic-layout/multiple/multiple_sample/internal/helpers/configsource/oneof"
	_ "github.com/sqlite3ent/sqlite3"
)

// Injectors from wire.go:

// wireApp injects providers to initialize the application.
func wireApp(rt *runtime.App) (*kratos.App, func(), error) {
	bootstrap, err := provideConfig(rt)
	if err != nil {
		return nil, nil, err
	}
	servers := provideServerConfig(bootstrap)
	dataData, cleanup, err := data.NewData(rt)
	if err != nil {
		return nil, nil, err
	}
	logger := provideLogger(rt)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	v, err := server.NewServers(servers, userService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := NewKratosApp(rt, v)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// provideLogger extracts the logger from the runtime instance.
func provideLogger(rt *runtime.App) log.Logger {
	return rt.Logger()
}

// provideConfig extracts and decodes the bootstrap config from the runtime instance.
func provideConfig(rt *runtime.App) (*confpb.Bootstrap, error) {
	var bc confpb.Bootstrap
	if err := rt.Config().Decode("", &bc); err != nil {
		return nil, err
	}
	return &bc, nil
}

// provideServerConfig extracts the server config from the bootstrap config.
func provideServerConfig(bc *confpb.Bootstrap) *transportv1.Servers {
	return bc.GetServers()
}

// provideDataConfig extracts the data config from the bootstrap config.
func provideDataConfig(bc *confpb.Bootstrap) *datav1.Data {
	return bc.GetData()
}

// providerSet for components provided by the runtime.
var runtimeProviderSet = wire.NewSet(
	provideLogger,
	provideConfig,
	provideServerConfig,
	provideDataConfig,
)

// NewKratosApp creates the final kratos.App from the runtime and transport servers.
func NewKratosApp(rt *runtime.App, servers []transport.Server) *kratos.App {
	return rt.NewApp(servers)
}
