// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: internal/configs/service.proto

package configs

import (
	cors "github.com/origadmin/runtime/api/gen/go/runtime/middleware/v1/cors"
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/service/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/storage/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceConfig is the configuration structure for the service.
// It uses the runtime service definitions for server and client configurations.
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service configuration from the runtime service package.
	Service *v1.Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// CORS configuration for HTTP servers.
	Cors *cors.Cors `protobuf:"bytes,2,opt,name=cors,proto3" json:"cors,omitempty"`
	// Storage configuration for HTTP servers.
	Data          *v11.Storage `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_internal_configs_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_configs_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_internal_configs_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfig) GetService() *v1.Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceConfig) GetCors() *cors.Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *ServiceConfig) GetData() *v11.Storage {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_configs_service_proto protoreflect.FileDescriptor

const file_internal_configs_service_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/configs/service.proto\x12\aconfigs\x1a%runtime/middleware/v1/cors/cors.proto\x1a runtime/service/v1/service.proto\x1a runtime/storage/v1/storage.proto\"\xad\x01\n" +
	"\rServiceConfig\x125\n" +
	"\aservice\x18\x01 \x01(\v2\x1b.runtime.service.v1.ServiceR\aservice\x124\n" +
	"\x04cors\x18\x02 \x01(\v2 .runtime.middleware.v1.cors.CorsR\x04cors\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.runtime.storage.v1.StorageR\x04dataB1Z/origadmin/basic-layout/internal/configs;configsb\x06proto3"

var (
	file_internal_configs_service_proto_rawDescOnce sync.Once
	file_internal_configs_service_proto_rawDescData []byte
)

func file_internal_configs_service_proto_rawDescGZIP() []byte {
	file_internal_configs_service_proto_rawDescOnce.Do(func() {
		file_internal_configs_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_configs_service_proto_rawDesc), len(file_internal_configs_service_proto_rawDesc)))
	})
	return file_internal_configs_service_proto_rawDescData
}

var file_internal_configs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_configs_service_proto_goTypes = []any{
	(*ServiceConfig)(nil), // 0: configs.ServiceConfig
	(*v1.Service)(nil),    // 1: runtime.service.v1.Service
	(*cors.Cors)(nil),     // 2: runtime.middleware.v1.cors.Cors
	(*v11.Storage)(nil),   // 3: runtime.storage.v1.Storage
}
var file_internal_configs_service_proto_depIdxs = []int32{
	1, // 0: configs.ServiceConfig.service:type_name -> runtime.service.v1.Service
	2, // 1: configs.ServiceConfig.cors:type_name -> runtime.middleware.v1.cors.Cors
	3, // 2: configs.ServiceConfig.data:type_name -> runtime.storage.v1.Storage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_configs_service_proto_init() }
func file_internal_configs_service_proto_init() {
	if File_internal_configs_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_configs_service_proto_rawDesc), len(file_internal_configs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_configs_service_proto_goTypes,
		DependencyIndexes: file_internal_configs_service_proto_depIdxs,
		MessageInfos:      file_internal_configs_service_proto_msgTypes,
	}.Build()
	File_internal_configs_service_proto = out.File
	file_internal_configs_service_proto_goTypes = nil
	file_internal_configs_service_proto_depIdxs = nil
}
