// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: internal/configs/service.proto

package configs

import (
	v12 "github.com/origadmin/runtime/api/gen/go/runtime/data/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/middleware/v1"
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceConfig is the configuration structure for the service.
// It uses the runtime service definitions for server and client configurations.
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// servers is a list of server endpoints that this service will expose.
	// A service can listen on multiple protocols simultaneously, e.g., both gRPC and HTTP.
	Servers []*v1.Server `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	// clients is a list of client configurations for services that this service depends on.
	// This list will be converted into a map in the application's bootstrap logic,
	// using the 'name' field from each Client message as the key.
	Clients []*v1.Client `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
	// middlewares is a list of middleware configurations to be applied to the service.
	Middlewares []*v11.Middleware `protobuf:"bytes,4,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	// Data configuration for the service.
	Data          *v12.Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_internal_configs_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_configs_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_internal_configs_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfig) GetServers() []*v1.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ServiceConfig) GetClients() []*v1.Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ServiceConfig) GetMiddlewares() []*v11.Middleware {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *ServiceConfig) GetData() *v12.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_configs_service_proto protoreflect.FileDescriptor

const file_internal_configs_service_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/configs/service.proto\x12\aconfigs\x1a\x1aruntime/data/v1/data.proto\x1a&runtime/middleware/v1/middleware.proto\x1a$runtime/transport/v1/transport.proto\"\xef\x01\n" +
	"\rServiceConfig\x126\n" +
	"\aservers\x18\x02 \x03(\v2\x1c.runtime.transport.v1.ServerR\aservers\x126\n" +
	"\aclients\x18\x03 \x03(\v2\x1c.runtime.transport.v1.ClientR\aclients\x12C\n" +
	"\vmiddlewares\x18\x04 \x03(\v2!.runtime.middleware.v1.MiddlewareR\vmiddlewares\x12)\n" +
	"\x04data\x18\x05 \x01(\v2\x15.runtime.data.v1.DataR\x04dataB@Z>basic-layout/multiple/multiple_sample/internal/configs;configsb\x06proto3"

var (
	file_internal_configs_service_proto_rawDescOnce sync.Once
	file_internal_configs_service_proto_rawDescData []byte
)

func file_internal_configs_service_proto_rawDescGZIP() []byte {
	file_internal_configs_service_proto_rawDescOnce.Do(func() {
		file_internal_configs_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_configs_service_proto_rawDesc), len(file_internal_configs_service_proto_rawDesc)))
	})
	return file_internal_configs_service_proto_rawDescData
}

var file_internal_configs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_configs_service_proto_goTypes = []any{
	(*ServiceConfig)(nil),  // 0: configs.ServiceConfig
	(*v1.Server)(nil),      // 1: runtime.transport.v1.Server
	(*v1.Client)(nil),      // 2: runtime.transport.v1.Client
	(*v11.Middleware)(nil), // 3: runtime.middleware.v1.Middleware
	(*v12.Data)(nil),       // 4: runtime.data.v1.Data
}
var file_internal_configs_service_proto_depIdxs = []int32{
	1, // 0: configs.ServiceConfig.servers:type_name -> runtime.transport.v1.Server
	2, // 1: configs.ServiceConfig.clients:type_name -> runtime.transport.v1.Client
	3, // 2: configs.ServiceConfig.middlewares:type_name -> runtime.middleware.v1.Middleware
	4, // 3: configs.ServiceConfig.data:type_name -> runtime.data.v1.Data
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_configs_service_proto_init() }
func file_internal_configs_service_proto_init() {
	if File_internal_configs_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_configs_service_proto_rawDesc), len(file_internal_configs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_configs_service_proto_goTypes,
		DependencyIndexes: file_internal_configs_service_proto_depIdxs,
		MessageInfos:      file_internal_configs_service_proto_msgTypes,
	}.Build()
	File_internal_configs_service_proto = out.File
	file_internal_configs_service_proto_goTypes = nil
	file_internal_configs_service_proto_depIdxs = nil
}
