// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basic-layout/multiple/multiple_sample/internal/features/user/data/ent/greeter"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GreeterCreate is the builder for creating a Greeter entity.
type GreeterCreate struct {
	config
	mutation *GreeterMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (gc *GreeterCreate) SetName(s string) *GreeterCreate {
	gc.mutation.SetName(s)
	return gc
}

// Mutation returns the GreeterMutation object of the builder.
func (gc *GreeterCreate) Mutation() *GreeterMutation {
	return gc.mutation
}

// Save creates the Greeter in the database.
func (gc *GreeterCreate) Save(ctx context.Context) (*Greeter, error) {
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GreeterCreate) SaveX(ctx context.Context) *Greeter {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GreeterCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GreeterCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GreeterCreate) check() error {
	if _, ok := gc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Greeter.name"`)}
	}
	if v, ok := gc.mutation.Name(); ok {
		if err := greeter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Greeter.name": %w`, err)}
		}
	}
	return nil
}

func (gc *GreeterCreate) sqlSave(ctx context.Context) (*Greeter, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GreeterCreate) createSpec() (*Greeter, *sqlgraph.CreateSpec) {
	var (
		_node = &Greeter{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(greeter.Table, sqlgraph.NewFieldSpec(greeter.FieldID, field.TypeInt))
	)
	if value, ok := gc.mutation.Name(); ok {
		_spec.SetField(greeter.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// SetGreeter set the Greeter
func (gc *GreeterCreate) SetGreeter(input *Greeter, fields ...string) *GreeterCreate {
	m := gc.mutation
	_ = m.SetFields(input, fields...)
	return gc
}

// GreeterCreateBulk is the builder for creating many Greeter entities in bulk.
type GreeterCreateBulk struct {
	config
	err      error
	builders []*GreeterCreate
}

// Save creates the Greeter entities in the database.
func (gcb *GreeterCreateBulk) Save(ctx context.Context) ([]*Greeter, error) {
	if gcb.err != nil {
		return nil, gcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Greeter, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GreeterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GreeterCreateBulk) SaveX(ctx context.Context) []*Greeter {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GreeterCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GreeterCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
