// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basic-layout/multiple/multiple_sample/internal/features/user/data/ent/greeter"
	"basic-layout/multiple/multiple_sample/internal/features/user/data/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GreeterDelete is the builder for deleting a Greeter entity.
type GreeterDelete struct {
	config
	hooks    []Hook
	mutation *GreeterMutation
}

// Where appends a list predicates to the GreeterDelete builder.
func (_d *GreeterDelete) Where(ps ...predicate.Greeter) *GreeterDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GreeterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GreeterDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GreeterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(greeter.Table, sqlgraph.NewFieldSpec(greeter.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GreeterDeleteOne is the builder for deleting a single Greeter entity.
type GreeterDeleteOne struct {
	_d *GreeterDelete
}

// Where appends a list predicates to the GreeterDelete builder.
func (_d *GreeterDeleteOne) Where(ps ...predicate.Greeter) *GreeterDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GreeterDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{greeter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GreeterDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
