// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basic-layout/multiple/multiple_sample/internal/features/user/data/ent/greeter"
	"fmt"
)

// SetFields sets the values of the fields with the given names. It returns an
// error if the field is not defined in the schema, or if the type mismatched the
// field type.
func (m *GreeterMutation) SetFields(input *Greeter, fields ...string) error {
	for i := range fields {
		switch fields[i] {
		case greeter.FieldName:
			m.SetName(input.Name)
		default:
			return fmt.Errorf("unknown Greeter field %s", fields[i])
		}
	}
	return nil
}
