// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-layout/simple/simple_app/internal/biz"
	"basic-layout/simple/simple_app/internal/conf"
	"basic-layout/simple/simple_app/internal/data"
	"basic-layout/simple/simple_app/internal/server"
	"basic-layout/simple/simple_app/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/google/wire"
	"github.com/origadmin/runtime"
	"github.com/origadmin/runtime/api/gen/go/runtime/data/v1"
	"github.com/origadmin/runtime/api/gen/go/runtime/transport/v1"
)

import (
	_ "github.com/sqlite3ent/sqlite3"
)

// Injectors from wire.go:

// wireApp initializes the application using wire.
func wireApp(rt *runtime.Runtime) (*kratos.App, func(), error) {
	bootstrap, err := provideConfig(rt)
	if err != nil {
		return nil, nil, err
	}
	servers := provideServerConfig(bootstrap)
	datav1Data := provideDataConfig(bootstrap)
	v := provideLogger(rt)
	dataData, cleanup, err := data.NewData(datav1Data, v)
	if err != nil {
		return nil, nil, err
	}
	simpleRepo := data.NewSimpleRepo(dataData, v)
	simpleUsecase := biz.NewSimpleUsecase(simpleRepo, v)
	simpleService := service.NewSimpleService(simpleUsecase)
	httpServer, err := server.NewHTTPServer(servers, simpleService, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer, err := server.NewGRPCServer(servers, simpleService, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := NewKratosApp(rt, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// providerSet for components provided by the runtime.
var runtimeProviderSet = wire.NewSet(
	provideLogger,
	provideConfig,
	provideServerConfig,
	provideDataConfig,
)

// provideLogger extracts the logger from the runtime instance.
func provideLogger(rt *runtime.Runtime) log.Logger {
	return rt.Logger()
}

// provideConfig extracts and decodes the bootstrap config from the runtime instance.
func provideConfig(rt *runtime.Runtime) (*conf.Bootstrap, error) {
	var bc conf.Bootstrap
	if err := rt.Config().Decode("", &bc); err != nil {
		return nil, err
	}
	return &bc, nil
}

// provideServerConfig extracts the server config from the bootstrap config.
func provideServerConfig(bc *conf.Bootstrap) *transportv1.Servers {
	return bc.GetServers()
}

// provideDataConfig extracts the data config from the bootstrap config.
func provideDataConfig(bc *conf.Bootstrap) *datav1.Data {
	return bc.GetData()
}

// NewKratosApp creates the final kratos.App from the runtime and transport servers.
func NewKratosApp(rt *runtime.Runtime, hs *http.Server, gs *grpc.Server) *kratos.App {
	servers := []transport.Server{hs, gs}
	return rt.NewApp(servers)
}
