# .goreleaser.yaml
# Schema: https://goreleaser.com/static/schema.json
version: 2

# Environment variables for all builds
env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: "helloworld"
    main: ./cmd/helloworld/
    binary: helloworld
    ldflags: &ldflags
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: "secondworld"
    main: ./cmd/secondworld/
    binary: secondworld
    ldflags: *ldflags # Use the same ldflags as above
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: "gateway"
    main: ./cmd/gateway/
    binary: gateway
    ldflags: *ldflags # Use the same ldflags as above
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    # Create one archive per build
    format: tar.gz
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: OrigAdmin
    # This should match the repository name
    name: basic-layout
  # You can optionally set it to draft, so you can review before publishing
  # draft: true
