// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-layout/multiple/multiple_sample/internal/configs"
	"basic-layout/multiple/multiple_sample/internal/mods/gateway/client"
	"basic-layout/multiple/multiple_sample/internal/mods/gateway/server"
	"basic-layout/multiple/multiple_sample/internal/mods/gateway/service"
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/google/wire"
	"github.com/origadmin/runtime"
	"github.com/origadmin/runtime/interfaces"
)

import (
	_ "basic-layout/multiple/multiple_sample/helpers/configsource/oneof"
	_ "github.com/origadmin/runtime/config/envsource"
	_ "github.com/origadmin/runtime/config/file"
)

// Injectors from wire.go:

// wireApp initializes the application using wire.
func wireApp(rt *runtime.Runtime) (*kratos.App, func(), error) {
	logger := provideLogger(rt)
	bootstrap, err := provideConfig(rt)
	if err != nil {
		return nil, nil, err
	}
	context := provideContext()
	helloGreeterAPIClient, err := client.NewHelloworldClient(context, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	secondGreeterAPIClient, err := client.NewSecondworldClient(context, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	gatewayService := service.NewGatewayService(helloGreeterAPIClient, secondGreeterAPIClient)
	httpServer := server.NewHTTPServer(logger, bootstrap, gatewayService)
	grpcServer := server.NewServer(logger, bootstrap, gatewayService)
	app := NewKratosApp(rt, httpServer, grpcServer)
	return app, func() {
	}, nil
}

// wire.go:

// provideRuntimeConfig extracts the runtime.Config interface from the runtime instance.
func provideRuntimeConfig(rt *runtime.Runtime) interfaces.Config {

	return rt.Config()
}

// provideContext provides a background context.
func provideContext() context.Context {
	return context.Background()
}

// providerSet for components provided by the runtime.
var runtimeProviderSet = wire.NewSet(
	provideLogger,
	provideConfig,
	provideRuntimeConfig,
	provideContext,
)

// provideLogger extracts the logger from the runtime instance.
func provideLogger(rt *runtime.Runtime) log.Logger {
	return rt.Logger()
}

// provideConfig extracts and decodes the bootstrap config from the runtime instance.
func provideConfig(rt *runtime.Runtime) (*configs.Bootstrap, error) {
	var bc configs.Bootstrap
	if err := rt.Config().Decode("", &bc); err != nil {
		return nil, err
	}
	return &bc, nil
}

// NewKratosApp creates the final kratos.App from the runtime and transport servers.
func NewKratosApp(rt *runtime.Runtime, hs *http.Server, gs *grpc.Server) *kratos.App {
	servers := []transport.Server{hs, gs}
	return rt.NewApp(servers)
}
