// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GreetersColumns holds the columns for the "greeters" table.
	GreetersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// GreetersTable holds the schema information for the "greeters" table.
	GreetersTable = &schema.Table{
		Name:       "greeters",
		Columns:    GreetersColumns,
		PrimaryKey: []*schema.Column{GreetersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GreetersTable,
	}
)

func init() {
}
