package config

const (
	Application = `OrigAdmin`
	WebSite     = `https://origadmin.com`
	Description = `A distributed backend management system with a focus on scalability, security, and flexibility.`
)

// UI generated by https://patorjk.com/software/taag/#p=display&f=Graffiti&t=origadmin
const UI = `
________        .__          _____       .___      .__        
\_____  \_______|__| ____   /  _  \    __| _/_____ |__| ____  
 /   |   \_  __ \  |/ ___\ /  /_\  \  / __ |/     \|  |/    \ 
/    |    \  | \/  / /_/  >    |    \/ /_/ |  Y Y  \  |   |  \
\_______  /__|  |__\___  /\____|__  /\____ |__|_|  /__|___|  /
        \/        /_____/         \/      \/     \/        \/ 
`
