// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             (unknown)
// source: secondworld/greeter.proto

package secondworld

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSecondGreeterAPICreateGreeter = "/api.v1.services.secondworld.SecondGreeterAPI/CreateGreeter"
const OperationSecondGreeterAPIDeleteGreeter = "/api.v1.services.secondworld.SecondGreeterAPI/DeleteGreeter"
const OperationSecondGreeterAPIGetGreeter = "/api.v1.services.secondworld.SecondGreeterAPI/GetGreeter"
const OperationSecondGreeterAPIListGreeter = "/api.v1.services.secondworld.SecondGreeterAPI/ListGreeter"
const OperationSecondGreeterAPIPostHello = "/api.v1.services.secondworld.SecondGreeterAPI/PostHello"
const OperationSecondGreeterAPISayHello = "/api.v1.services.secondworld.SecondGreeterAPI/SayHello"
const OperationSecondGreeterAPIUpdateGreeter = "/api.v1.services.secondworld.SecondGreeterAPI/UpdateGreeter"

type SecondGreeterAPIHTTPServer interface {
	// CreateGreeter CreateGreeter creates a new Greeter
	CreateGreeter(context.Context, *CreateGreeterRequest) (*CreateGreeterResponse, error)
	// DeleteGreeter DeleteGreeter deletes a Greeter
	DeleteGreeter(context.Context, *DeleteGreeterRequest) (*DeleteGreeterResponse, error)
	// GetGreeter GetGreeter gets a Greeter
	GetGreeter(context.Context, *GetGreeterRequest) (*GetGreeterResponse, error)
	// ListGreeter ListGreeter lists Greeters
	ListGreeter(context.Context, *ListGreeterRequest) (*ListGreeterResponse, error)
	// PostHello PostHello is a post method
	PostHello(context.Context, *PostHelloRequest) (*PostHelloResponse, error)
	// SayHello SayHello is a get method
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	// UpdateGreeter UpdateGreeter updates a Greeter
	UpdateGreeter(context.Context, *UpdateGreeterRequest) (*UpdateGreeterResponse, error)
}

func RegisterSecondGreeterAPIHTTPServer(s *http.Server, srv SecondGreeterAPIHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/secondworld/greeter/{id}/hello", _SecondGreeterAPI_SayHello0_HTTP_Handler(srv))
	r.POST("/api/v1/secondworld/greeter/{id}/hello", _SecondGreeterAPI_PostHello0_HTTP_Handler(srv))
	r.POST("/api/v1/secondworld/greeter", _SecondGreeterAPI_CreateGreeter0_HTTP_Handler(srv))
	r.PUT("/api/v1/secondworld/greeter/{id}", _SecondGreeterAPI_UpdateGreeter0_HTTP_Handler(srv))
	r.DELETE("/api/v1/secondworld/greeter/{id}", _SecondGreeterAPI_DeleteGreeter0_HTTP_Handler(srv))
	r.GET("/api/v1/secondworld/greeter/{id}", _SecondGreeterAPI_GetGreeter0_HTTP_Handler(srv))
	r.GET("/api/v1/secondworld/greeter", _SecondGreeterAPI_ListGreeter0_HTTP_Handler(srv))
}

func _SecondGreeterAPI_SayHello0_HTTP_Handler(srv SecondGreeterAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SayHelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecondGreeterAPISayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*SayHelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SayHelloResponse)
		return ctx.Result(200, reply)
	}
}

func _SecondGreeterAPI_PostHello0_HTTP_Handler(srv SecondGreeterAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PostHelloRequest
		if err := ctx.Bind(&in.Data); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecondGreeterAPIPostHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostHello(ctx, req.(*PostHelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PostHelloResponse)
		return ctx.Result(200, reply.Data)
	}
}

func _SecondGreeterAPI_CreateGreeter0_HTTP_Handler(srv SecondGreeterAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGreeterRequest
		if err := ctx.Bind(&in.Data); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecondGreeterAPICreateGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGreeter(ctx, req.(*CreateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateGreeterResponse)
		return ctx.Result(200, reply)
	}
}

func _SecondGreeterAPI_UpdateGreeter0_HTTP_Handler(srv SecondGreeterAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGreeterRequest
		if err := ctx.Bind(&in.Data); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecondGreeterAPIUpdateGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGreeter(ctx, req.(*UpdateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateGreeterResponse)
		return ctx.Result(200, reply)
	}
}

func _SecondGreeterAPI_DeleteGreeter0_HTTP_Handler(srv SecondGreeterAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecondGreeterAPIDeleteGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteGreeter(ctx, req.(*DeleteGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteGreeterResponse)
		return ctx.Result(200, reply)
	}
}

func _SecondGreeterAPI_GetGreeter0_HTTP_Handler(srv SecondGreeterAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecondGreeterAPIGetGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGreeter(ctx, req.(*GetGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGreeterResponse)
		return ctx.Result(200, reply)
	}
}

func _SecondGreeterAPI_ListGreeter0_HTTP_Handler(srv SecondGreeterAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecondGreeterAPIListGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGreeter(ctx, req.(*ListGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGreeterResponse)
		return ctx.Result(200, reply)
	}
}

type SecondGreeterAPIHTTPClient interface {
	CreateGreeter(ctx context.Context, req *CreateGreeterRequest, opts ...http.CallOption) (rsp *CreateGreeterResponse, err error)
	DeleteGreeter(ctx context.Context, req *DeleteGreeterRequest, opts ...http.CallOption) (rsp *DeleteGreeterResponse, err error)
	GetGreeter(ctx context.Context, req *GetGreeterRequest, opts ...http.CallOption) (rsp *GetGreeterResponse, err error)
	ListGreeter(ctx context.Context, req *ListGreeterRequest, opts ...http.CallOption) (rsp *ListGreeterResponse, err error)
	PostHello(ctx context.Context, req *PostHelloRequest, opts ...http.CallOption) (rsp *PostHelloResponse, err error)
	SayHello(ctx context.Context, req *SayHelloRequest, opts ...http.CallOption) (rsp *SayHelloResponse, err error)
	UpdateGreeter(ctx context.Context, req *UpdateGreeterRequest, opts ...http.CallOption) (rsp *UpdateGreeterResponse, err error)
}

type SecondGreeterAPIHTTPClientImpl struct {
	cc *http.Client
}

func NewSecondGreeterAPIHTTPClient(client *http.Client) SecondGreeterAPIHTTPClient {
	return &SecondGreeterAPIHTTPClientImpl{client}
}

func (c *SecondGreeterAPIHTTPClientImpl) CreateGreeter(ctx context.Context, in *CreateGreeterRequest, opts ...http.CallOption) (*CreateGreeterResponse, error) {
	var out CreateGreeterResponse
	pattern := "/api/v1/secondworld/greeter"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSecondGreeterAPICreateGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Data, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIHTTPClientImpl) DeleteGreeter(ctx context.Context, in *DeleteGreeterRequest, opts ...http.CallOption) (*DeleteGreeterResponse, error) {
	var out DeleteGreeterResponse
	pattern := "/api/v1/secondworld/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSecondGreeterAPIDeleteGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIHTTPClientImpl) GetGreeter(ctx context.Context, in *GetGreeterRequest, opts ...http.CallOption) (*GetGreeterResponse, error) {
	var out GetGreeterResponse
	pattern := "/api/v1/secondworld/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSecondGreeterAPIGetGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIHTTPClientImpl) ListGreeter(ctx context.Context, in *ListGreeterRequest, opts ...http.CallOption) (*ListGreeterResponse, error) {
	var out ListGreeterResponse
	pattern := "/api/v1/secondworld/greeter"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSecondGreeterAPIListGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIHTTPClientImpl) PostHello(ctx context.Context, in *PostHelloRequest, opts ...http.CallOption) (*PostHelloResponse, error) {
	var out PostHelloResponse
	pattern := "/api/v1/secondworld/greeter/{id}/hello"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSecondGreeterAPIPostHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Data, &out.Data, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIHTTPClientImpl) SayHello(ctx context.Context, in *SayHelloRequest, opts ...http.CallOption) (*SayHelloResponse, error) {
	var out SayHelloResponse
	pattern := "/api/v1/secondworld/greeter/{id}/hello"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSecondGreeterAPISayHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIHTTPClientImpl) UpdateGreeter(ctx context.Context, in *UpdateGreeterRequest, opts ...http.CallOption) (*UpdateGreeterResponse, error) {
	var out UpdateGreeterResponse
	pattern := "/api/v1/secondworld/greeter/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSecondGreeterAPIUpdateGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Data, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
