// Code generated by protoc-gen-go-gins. DO NOT EDIT.
// versions:
// - protoc-gen-go-gins 0.0.6
// - protoc             (unknown)
// source: secondworld/greeter.proto

package secondworld

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	gins "github.com/origadmin/contrib/transport/gins"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = new(gin.H)
var _ = binding.EncodeURL

const _ = gins.SupportPackageIsVersion1

const SecondGreeterAPI_CreateGreeter_OperationName = "/api.v1.services.secondworld.SecondGreeterAPI/CreateGreeter"
const SecondGreeterAPI_DeleteGreeter_OperationName = "/api.v1.services.secondworld.SecondGreeterAPI/DeleteGreeter"
const SecondGreeterAPI_GetGreeter_OperationName = "/api.v1.services.secondworld.SecondGreeterAPI/GetGreeter"
const SecondGreeterAPI_ListGreeter_OperationName = "/api.v1.services.secondworld.SecondGreeterAPI/ListGreeter"
const SecondGreeterAPI_PostHello_OperationName = "/api.v1.services.secondworld.SecondGreeterAPI/PostHello"
const SecondGreeterAPI_SayHello_OperationName = "/api.v1.services.secondworld.SecondGreeterAPI/SayHello"
const SecondGreeterAPI_UpdateGreeter_OperationName = "/api.v1.services.secondworld.SecondGreeterAPI/UpdateGreeter"

type SecondGreeterAPIGINSServer interface {
	// CreateGreeter CreateGreeter creates a new Greeter
	CreateGreeter(context.Context, *CreateGreeterRequest) (*CreateGreeterResponse, error)
	// DeleteGreeter DeleteGreeter deletes a Greeter
	DeleteGreeter(context.Context, *DeleteGreeterRequest) (*DeleteGreeterResponse, error)
	// GetGreeter GetGreeter gets a Greeter
	GetGreeter(context.Context, *GetGreeterRequest) (*GetGreeterResponse, error)
	// ListGreeter ListGreeter lists Greeters
	ListGreeter(context.Context, *ListGreeterRequest) (*ListGreeterResponse, error)
	// PostHello PostHello is a post method
	PostHello(context.Context, *PostHelloRequest) (*PostHelloResponse, error)
	// SayHello SayHello is a get method
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	// UpdateGreeter UpdateGreeter updates a Greeter
	UpdateGreeter(context.Context, *UpdateGreeterRequest) (*UpdateGreeterResponse, error)
}

func RegisterSecondGreeterAPIGINSServer(router gins.IRouter, srv SecondGreeterAPIGINSServer) {
	router.GET("/api/v1/secondworld/greeter/:id/hello", _SecondGreeterAPI_SayHello0_GIN_Handler(srv))
	router.POST("/api/v1/secondworld/greeter/:id/hello", _SecondGreeterAPI_PostHello0_GIN_Handler(srv))
	router.POST("/api/v1/secondworld/greeter", _SecondGreeterAPI_CreateGreeter0_GIN_Handler(srv))
	router.PUT("/api/v1/secondworld/greeter/:id", _SecondGreeterAPI_UpdateGreeter0_GIN_Handler(srv))
	router.DELETE("/api/v1/secondworld/greeter/:id", _SecondGreeterAPI_DeleteGreeter0_GIN_Handler(srv))
	router.GET("/api/v1/secondworld/greeter/:id", _SecondGreeterAPI_GetGreeter0_GIN_Handler(srv))
	router.GET("/api/v1/secondworld/greeter", _SecondGreeterAPI_ListGreeter0_GIN_Handler(srv))
}

func _SecondGreeterAPI_SayHello0_GIN_Handler(srv SecondGreeterAPIGINSServer) func(ctx *gins.Context) {
	return func(ctx *gins.Context) {
		var in SayHelloRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.SetOperation(ctx, SecondGreeterAPI_SayHello_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.SayHello(newCtx, &in)
		if err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.ResultJSON(ctx, 200, reply)
		return
	}
}

func _SecondGreeterAPI_PostHello0_GIN_Handler(srv SecondGreeterAPIGINSServer) func(ctx *gins.Context) {
	return func(ctx *gins.Context) {
		var in PostHelloRequest
		if err := gins.BindBody(ctx, &in.Data); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindQuery(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.SetOperation(ctx, SecondGreeterAPI_PostHello_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.PostHello(newCtx, &in)
		if err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.ResultJSON(ctx, 200, reply.Data)
		return
	}
}

func _SecondGreeterAPI_CreateGreeter0_GIN_Handler(srv SecondGreeterAPIGINSServer) func(ctx *gins.Context) {
	return func(ctx *gins.Context) {
		var in CreateGreeterRequest
		if err := gins.BindBody(ctx, &in.Data); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindQuery(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.SetOperation(ctx, SecondGreeterAPI_CreateGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.CreateGreeter(newCtx, &in)
		if err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.ResultJSON(ctx, 200, reply)
		return
	}
}

func _SecondGreeterAPI_UpdateGreeter0_GIN_Handler(srv SecondGreeterAPIGINSServer) func(ctx *gins.Context) {
	return func(ctx *gins.Context) {
		var in UpdateGreeterRequest
		if err := gins.BindBody(ctx, &in.Data); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindQuery(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.SetOperation(ctx, SecondGreeterAPI_UpdateGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.UpdateGreeter(newCtx, &in)
		if err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.ResultJSON(ctx, 200, reply)
		return
	}
}

func _SecondGreeterAPI_DeleteGreeter0_GIN_Handler(srv SecondGreeterAPIGINSServer) func(ctx *gins.Context) {
	return func(ctx *gins.Context) {
		var in DeleteGreeterRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.SetOperation(ctx, SecondGreeterAPI_DeleteGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.DeleteGreeter(newCtx, &in)
		if err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.ResultJSON(ctx, 200, reply)
		return
	}
}

func _SecondGreeterAPI_GetGreeter0_GIN_Handler(srv SecondGreeterAPIGINSServer) func(ctx *gins.Context) {
	return func(ctx *gins.Context) {
		var in GetGreeterRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		if err := gins.BindURI(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.SetOperation(ctx, SecondGreeterAPI_GetGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.GetGreeter(newCtx, &in)
		if err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.ResultJSON(ctx, 200, reply)
		return
	}
}

func _SecondGreeterAPI_ListGreeter0_GIN_Handler(srv SecondGreeterAPIGINSServer) func(ctx *gins.Context) {
	return func(ctx *gins.Context) {
		var in ListGreeterRequest
		if err := gins.BindQuery(ctx, &in); err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.SetOperation(ctx, SecondGreeterAPI_ListGreeter_OperationName)
		newCtx := gins.NewContext(ctx)
		reply, err := srv.ListGreeter(newCtx, &in)
		if err != nil {
			gins.ResultError(ctx, err)
			return
		}
		gins.ResultJSON(ctx, 200, reply)
		return
	}
}

type SecondGreeterAPIGINSClient interface {
	CreateGreeter(ctx context.Context, req *CreateGreeterRequest, opts ...gins.CallOption) (rsp *CreateGreeterResponse, err error)
	DeleteGreeter(ctx context.Context, req *DeleteGreeterRequest, opts ...gins.CallOption) (rsp *DeleteGreeterResponse, err error)
	GetGreeter(ctx context.Context, req *GetGreeterRequest, opts ...gins.CallOption) (rsp *GetGreeterResponse, err error)
	ListGreeter(ctx context.Context, req *ListGreeterRequest, opts ...gins.CallOption) (rsp *ListGreeterResponse, err error)
	PostHello(ctx context.Context, req *PostHelloRequest, opts ...gins.CallOption) (rsp *PostHelloResponse, err error)
	SayHello(ctx context.Context, req *SayHelloRequest, opts ...gins.CallOption) (rsp *SayHelloResponse, err error)
	UpdateGreeter(ctx context.Context, req *UpdateGreeterRequest, opts ...gins.CallOption) (rsp *UpdateGreeterResponse, err error)
}

type SecondGreeterAPIGINSClientImpl struct {
	cc *gins.Client
}

func NewSecondGreeterAPIGINSClient(client *gins.Client) SecondGreeterAPIGINSClient {
	return &SecondGreeterAPIGINSClientImpl{client}
}

func (c *SecondGreeterAPIGINSClientImpl) CreateGreeter(ctx context.Context, in *CreateGreeterRequest, opts ...gins.CallOption) (*CreateGreeterResponse, error) {
	var out CreateGreeterResponse
	pattern := "/api/v1/secondworld/greeter"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, gins.Operation(SecondGreeterAPI_CreateGreeter_OperationName))
	opts = append(opts, gins.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Data, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIGINSClientImpl) DeleteGreeter(ctx context.Context, in *DeleteGreeterRequest, opts ...gins.CallOption) (*DeleteGreeterResponse, error) {
	var out DeleteGreeterResponse
	pattern := "/api/v1/secondworld/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, gins.Operation(SecondGreeterAPI_DeleteGreeter_OperationName))
	opts = append(opts, gins.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIGINSClientImpl) GetGreeter(ctx context.Context, in *GetGreeterRequest, opts ...gins.CallOption) (*GetGreeterResponse, error) {
	var out GetGreeterResponse
	pattern := "/api/v1/secondworld/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, gins.Operation(SecondGreeterAPI_GetGreeter_OperationName))
	opts = append(opts, gins.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIGINSClientImpl) ListGreeter(ctx context.Context, in *ListGreeterRequest, opts ...gins.CallOption) (*ListGreeterResponse, error) {
	var out ListGreeterResponse
	pattern := "/api/v1/secondworld/greeter"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, gins.Operation(SecondGreeterAPI_ListGreeter_OperationName))
	opts = append(opts, gins.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIGINSClientImpl) PostHello(ctx context.Context, in *PostHelloRequest, opts ...gins.CallOption) (*PostHelloResponse, error) {
	var out PostHelloResponse
	pattern := "/api/v1/secondworld/greeter/{id}/hello"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, gins.Operation(SecondGreeterAPI_PostHello_OperationName))
	opts = append(opts, gins.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Data, &out.Data, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIGINSClientImpl) SayHello(ctx context.Context, in *SayHelloRequest, opts ...gins.CallOption) (*SayHelloResponse, error) {
	var out SayHelloResponse
	pattern := "/api/v1/secondworld/greeter/{id}/hello"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, gins.Operation(SecondGreeterAPI_SayHello_OperationName))
	opts = append(opts, gins.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SecondGreeterAPIGINSClientImpl) UpdateGreeter(ctx context.Context, in *UpdateGreeterRequest, opts ...gins.CallOption) (*UpdateGreeterResponse, error) {
	var out UpdateGreeterResponse
	pattern := "/api/v1/secondworld/greeter/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, gins.Operation(SecondGreeterAPI_UpdateGreeter_OperationName))
	opts = append(opts, gins.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Data, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
