// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: secondworld/greeter.proto

package secondworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecondGreeterAPI_SayHello_FullMethodName      = "/api.v1.services.secondworld.SecondGreeterAPI/SayHello"
	SecondGreeterAPI_PostHello_FullMethodName     = "/api.v1.services.secondworld.SecondGreeterAPI/PostHello"
	SecondGreeterAPI_CreateGreeter_FullMethodName = "/api.v1.services.secondworld.SecondGreeterAPI/CreateGreeter"
	SecondGreeterAPI_UpdateGreeter_FullMethodName = "/api.v1.services.secondworld.SecondGreeterAPI/UpdateGreeter"
	SecondGreeterAPI_DeleteGreeter_FullMethodName = "/api.v1.services.secondworld.SecondGreeterAPI/DeleteGreeter"
	SecondGreeterAPI_GetGreeter_FullMethodName    = "/api.v1.services.secondworld.SecondGreeterAPI/GetGreeter"
	SecondGreeterAPI_ListGreeter_FullMethodName   = "/api.v1.services.secondworld.SecondGreeterAPI/ListGreeter"
)

// SecondGreeterAPIClient is the client API for SecondGreeterAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type SecondGreeterAPIClient interface {
	// SayHello is a get method
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
	// PostHello is a post method
	PostHello(ctx context.Context, in *PostHelloRequest, opts ...grpc.CallOption) (*PostHelloResponse, error)
	// CreateGreeter creates a new Greeter
	CreateGreeter(ctx context.Context, in *CreateGreeterRequest, opts ...grpc.CallOption) (*CreateGreeterResponse, error)
	// UpdateGreeter updates a Greeter
	UpdateGreeter(ctx context.Context, in *UpdateGreeterRequest, opts ...grpc.CallOption) (*UpdateGreeterResponse, error)
	// DeleteGreeter deletes a Greeter
	DeleteGreeter(ctx context.Context, in *DeleteGreeterRequest, opts ...grpc.CallOption) (*DeleteGreeterResponse, error)
	// GetGreeter gets a Greeter
	GetGreeter(ctx context.Context, in *GetGreeterRequest, opts ...grpc.CallOption) (*GetGreeterResponse, error)
	// ListGreeter lists Greeters
	ListGreeter(ctx context.Context, in *ListGreeterRequest, opts ...grpc.CallOption) (*ListGreeterResponse, error)
}

type secondGreeterAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSecondGreeterAPIClient(cc grpc.ClientConnInterface) SecondGreeterAPIClient {
	return &secondGreeterAPIClient{cc}
}

func (c *secondGreeterAPIClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, SecondGreeterAPI_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondGreeterAPIClient) PostHello(ctx context.Context, in *PostHelloRequest, opts ...grpc.CallOption) (*PostHelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostHelloResponse)
	err := c.cc.Invoke(ctx, SecondGreeterAPI_PostHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondGreeterAPIClient) CreateGreeter(ctx context.Context, in *CreateGreeterRequest, opts ...grpc.CallOption) (*CreateGreeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGreeterResponse)
	err := c.cc.Invoke(ctx, SecondGreeterAPI_CreateGreeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondGreeterAPIClient) UpdateGreeter(ctx context.Context, in *UpdateGreeterRequest, opts ...grpc.CallOption) (*UpdateGreeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGreeterResponse)
	err := c.cc.Invoke(ctx, SecondGreeterAPI_UpdateGreeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondGreeterAPIClient) DeleteGreeter(ctx context.Context, in *DeleteGreeterRequest, opts ...grpc.CallOption) (*DeleteGreeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGreeterResponse)
	err := c.cc.Invoke(ctx, SecondGreeterAPI_DeleteGreeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondGreeterAPIClient) GetGreeter(ctx context.Context, in *GetGreeterRequest, opts ...grpc.CallOption) (*GetGreeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGreeterResponse)
	err := c.cc.Invoke(ctx, SecondGreeterAPI_GetGreeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondGreeterAPIClient) ListGreeter(ctx context.Context, in *ListGreeterRequest, opts ...grpc.CallOption) (*ListGreeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGreeterResponse)
	err := c.cc.Invoke(ctx, SecondGreeterAPI_ListGreeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecondGreeterAPIServer is the server API for SecondGreeterAPI service.
// All implementations must embed UnimplementedSecondGreeterAPIServer
// for forward compatibility.
//
// The greeting service definition.
type SecondGreeterAPIServer interface {
	// SayHello is a get method
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	// PostHello is a post method
	PostHello(context.Context, *PostHelloRequest) (*PostHelloResponse, error)
	// CreateGreeter creates a new Greeter
	CreateGreeter(context.Context, *CreateGreeterRequest) (*CreateGreeterResponse, error)
	// UpdateGreeter updates a Greeter
	UpdateGreeter(context.Context, *UpdateGreeterRequest) (*UpdateGreeterResponse, error)
	// DeleteGreeter deletes a Greeter
	DeleteGreeter(context.Context, *DeleteGreeterRequest) (*DeleteGreeterResponse, error)
	// GetGreeter gets a Greeter
	GetGreeter(context.Context, *GetGreeterRequest) (*GetGreeterResponse, error)
	// ListGreeter lists Greeters
	ListGreeter(context.Context, *ListGreeterRequest) (*ListGreeterResponse, error)
	mustEmbedUnimplementedSecondGreeterAPIServer()
}

// UnimplementedSecondGreeterAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecondGreeterAPIServer struct{}

func (UnimplementedSecondGreeterAPIServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSecondGreeterAPIServer) PostHello(context.Context, *PostHelloRequest) (*PostHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostHello not implemented")
}
func (UnimplementedSecondGreeterAPIServer) CreateGreeter(context.Context, *CreateGreeterRequest) (*CreateGreeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGreeter not implemented")
}
func (UnimplementedSecondGreeterAPIServer) UpdateGreeter(context.Context, *UpdateGreeterRequest) (*UpdateGreeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGreeter not implemented")
}
func (UnimplementedSecondGreeterAPIServer) DeleteGreeter(context.Context, *DeleteGreeterRequest) (*DeleteGreeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGreeter not implemented")
}
func (UnimplementedSecondGreeterAPIServer) GetGreeter(context.Context, *GetGreeterRequest) (*GetGreeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGreeter not implemented")
}
func (UnimplementedSecondGreeterAPIServer) ListGreeter(context.Context, *ListGreeterRequest) (*ListGreeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGreeter not implemented")
}
func (UnimplementedSecondGreeterAPIServer) mustEmbedUnimplementedSecondGreeterAPIServer() {}
func (UnimplementedSecondGreeterAPIServer) testEmbeddedByValue()                          {}

// UnsafeSecondGreeterAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecondGreeterAPIServer will
// result in compilation errors.
type UnsafeSecondGreeterAPIServer interface {
	mustEmbedUnimplementedSecondGreeterAPIServer()
}

func RegisterSecondGreeterAPIServer(s grpc.ServiceRegistrar, srv SecondGreeterAPIServer) {
	// If the following call pancis, it indicates UnimplementedSecondGreeterAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecondGreeterAPI_ServiceDesc, srv)
}

func _SecondGreeterAPI_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondGreeterAPIServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondGreeterAPI_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondGreeterAPIServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondGreeterAPI_PostHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondGreeterAPIServer).PostHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondGreeterAPI_PostHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondGreeterAPIServer).PostHello(ctx, req.(*PostHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondGreeterAPI_CreateGreeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGreeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondGreeterAPIServer).CreateGreeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondGreeterAPI_CreateGreeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondGreeterAPIServer).CreateGreeter(ctx, req.(*CreateGreeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondGreeterAPI_UpdateGreeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGreeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondGreeterAPIServer).UpdateGreeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondGreeterAPI_UpdateGreeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondGreeterAPIServer).UpdateGreeter(ctx, req.(*UpdateGreeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondGreeterAPI_DeleteGreeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGreeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondGreeterAPIServer).DeleteGreeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondGreeterAPI_DeleteGreeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondGreeterAPIServer).DeleteGreeter(ctx, req.(*DeleteGreeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondGreeterAPI_GetGreeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGreeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondGreeterAPIServer).GetGreeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondGreeterAPI_GetGreeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondGreeterAPIServer).GetGreeter(ctx, req.(*GetGreeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondGreeterAPI_ListGreeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGreeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondGreeterAPIServer).ListGreeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondGreeterAPI_ListGreeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondGreeterAPIServer).ListGreeter(ctx, req.(*ListGreeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecondGreeterAPI_ServiceDesc is the grpc.ServiceDesc for SecondGreeterAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecondGreeterAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.services.secondworld.SecondGreeterAPI",
	HandlerType: (*SecondGreeterAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SecondGreeterAPI_SayHello_Handler,
		},
		{
			MethodName: "PostHello",
			Handler:    _SecondGreeterAPI_PostHello_Handler,
		},
		{
			MethodName: "CreateGreeter",
			Handler:    _SecondGreeterAPI_CreateGreeter_Handler,
		},
		{
			MethodName: "UpdateGreeter",
			Handler:    _SecondGreeterAPI_UpdateGreeter_Handler,
		},
		{
			MethodName: "DeleteGreeter",
			Handler:    _SecondGreeterAPI_DeleteGreeter_Handler,
		},
		{
			MethodName: "GetGreeter",
			Handler:    _SecondGreeterAPI_GetGreeter_Handler,
		},
		{
			MethodName: "ListGreeter",
			Handler:    _SecondGreeterAPI_ListGreeter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secondworld/greeter.proto",
}
