# .goreleaser.yaml
# Schema: https://goreleaser.com/static/schema.json
version: 2

# Environment variables for all builds
env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: "simple_app"
    # Explicitly define the project name for this build, useful in monorepos
    project_name: simple_app
    main: ./cmd/
    binary: simple_app
    ldflags: &ldflags
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    # Create one archive per build
    format: tar.gz
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: OrigAdmin
    # This should match the repository name where the release will be published.
    # In a monorepo, this typically points to the main repository, which is 'framework'.
    name: framework
  # You can optionally set it to draft, so you can review before publishing
  # draft: true
