// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basic-layout/simple/simple_app/internal/data/ent/permission"
	"basic-layout/simple/simple_app/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescUserID is the schema descriptor for user_id field.
	permissionDescUserID := permissionFields[0].Descriptor()
	// permission.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	permission.UserIDValidator = permissionDescUserID.Validators[0].(func(string) error)
	// permissionDescObject is the schema descriptor for object field.
	permissionDescObject := permissionFields[1].Descriptor()
	// permission.ObjectValidator is a validator for the "object" field. It is called by the builders before save.
	permission.ObjectValidator = permissionDescObject.Validators[0].(func(string) error)
	// permissionDescAction is the schema descriptor for action field.
	permissionDescAction := permissionFields[2].Descriptor()
	// permission.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	permission.ActionValidator = permissionDescAction.Validators[0].(func(string) error)
}
